[package]
name = "mkicon"
version = "0.1.1"
authors = ["marm.nakamura <hey_kitarou@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinybmp = "0.2.3"
